feat: add user lists [ALKL-58]
matixezor/AlkohoLove-backend-service pull request #24
Opened 2022-05-29 13:59 UTC by Thyme1

2022-05-30 18:07 UTC, matixezor requested changes

2022-05-30 18:07 UTC, matixezor commented on src/infrastructure/database/models/user_list/search_history_database_handler.py
> +        search_history = list(search_history_collection.find({'user_id': ObjectId(user_id)}, {'alcohols': 1}))
może find_one?

2022-05-30 18:07 UTC, matixezor commented on src/infrastructure/database/models/user_list/search_history_database_handler.py
> +        alcohol_ids = [a_dict['alcohol_id'] for a_dict in search_history]
zrób to jednym for'em zamiast dwoma
po prostu:
for alcohol_dict in search_history:
    alcohol_ids.append(..)
    dates.append(...)

2022-05-30 18:07 UTC, matixezor commented on src/api/me.py
> +async def delete_alcohol_form_wishlist(
from* w innych miejscach to samo.
Zastanawiam się, czy nie lepiej byłoby zwracać zaktualizowane listy po operacjach na nich... 🤔 Pewnie pytanie do frontu co im bardziej pasuje

2022-05-30 18:07 UTC, matixezor commented on src/infrastructure/database/models/user_list/wishlist_database_handler.py
> +        wishlist = list(wishlist_collection.find({'user_id': ObjectId(user_id)}, {'alcohols': 1}))
find_one

2022-05-30 18:07 UTC, matixezor commented on src/utils/list_fixtures.py
> +WISHLIST_FIXTURE = [
to powinno się znaleźć w paczce tests

2022-05-30 21:42 UTC, Thyme1 commented on src/infrastructure/database/models/user_list/search_history.py
> +    alcohols: list[SearchHistoryEntry]
To jest lista SearchHistoryEntry a tam są alkohole i daty (zmienie nazwe na alcohols_and_dates)
Jeszcze nie wiem czy coś tu nie zmienie bo ogólnie to kwestia tego że zwracam to jako tuple (Alcohol, date)

2022-05-30 21:43 UTC, Thyme1 commented on src/domain/user_list/search_history.py
> +class SearchHistoryEntry(typing.NamedTuple):
To jest lista SearchHistoryEntry a tam są alkohole i daty (zmienie nazwe na alcohols_and_dates)
Jeszcze nie wiem czy coś tu nie zmienie bo ogólnie to kwestia tego że zwracam to jako tuple (Alcohol, date)

2022-05-30 22:11 UTC, Thyme1 commented on src/domain/user_list/search_history.py
> +class SearchHistoryEntry(typing.NamedTuple):
Na ten moment dałem ładniejszy import, jutro mogę pomyśleć jak to zmienić

2022-05-31 17:59 UTC, matixezor submitted a review, later dismissed

2022-05-31 18:26 UTC, matixezor approved these changes

2022-05-31 18:30 UTC, merged