Alkl 111 user tags api
matixezor/AlkohoLove-backend-service pull request #25
Opened 2022-05-29 15:55 UTC by Hiiiiiku

2022-05-29 16:57 UTC, Thyme1 submitted a review, later dismissed

2022-05-29 16:57 UTC, Thyme1 commented on init_db/008-user_tags_collection.js
> +                description: 'must be a string'let tag = {
Tu coś nie tak jest

2022-05-29 17:01 UTC, Hiiiiiku commented on init_db/008-user_tags_collection.js
> +                description: 'must be a string'let tag = {
Faktycznie, dzięki. Przez przypadek wyrzuciłem coś z tego pliku i potem cofałem XD

2022-05-30 18:11 UTC, matixezor requested changes

2022-05-30 18:11 UTC, matixezor commented on src/api/me.py
> +        tag_id: str,
wrzuciłbym to jako path param

2022-05-30 18:11 UTC, matixezor commented on src/api/me.py
> +        tag_id: str,
wrzuciłbym to jako path param

2022-05-30 18:11 UTC, matixezor commented on src/api/me.py
> +        alcohol_id: str,
wrzuciłbym to jako path param

2022-05-30 18:11 UTC, matixezor commented on src/api/me.py
> +        tag_id: str,
wrzuciłbym to jako path param

2022-05-30 18:11 UTC, matixezor commented on src/api/me.py
> +        alcohol_id: str,
wrzuciłbym to jako path param

2022-05-30 18:11 UTC, matixezor commented on src/api/me.py
> +        tag_id: str,
wrzuciłbym to jako path param

2022-05-30 18:11 UTC, matixezor commented on src/api/me.py
> +        tag_id: str,
wrzuciłbym to jako path param

2022-05-30 18:11 UTC, matixezor commented on src/infrastructure/database/models/user_tag/user_tag_database_handler.py
> +            tag_collection.find({'_id': ObjectId(tag_id)}, {'alcohols': 1})
fiind_one?

2022-05-31 15:37 UTC, matixezor commented on src/api/me.py
> +    path='/tags/alcohol/{tag_id}/{alcohol_id}',
/tags/{tag_id}/alcohol/{alcohol_id}

2022-05-31 15:38 UTC, matixezor commented on init_db/008-user_tags_collection.js
> +                description: 'list of alcohols',
list of alcohol ids może tak

2022-05-31 15:38 UTC, matixezor commented on src/api/me.py
> +    path='/tags/{tag_id}/{tag_name}',
tag_name może być w query paramsie

2022-05-31 15:38 UTC, matixezor commented on src/api/me.py
> +    path='/tags/alcohols/{tag_id}',
/tags/{tag_id}/alcohols

2022-05-31 15:55 UTC, matixezor approved these changes

2022-05-31 16:24 UTC, merged