feat: add api for followers [ALKL-74]
matixezor/AlkohoLove-backend-service pull request #26
Opened 2022-05-31 19:37 UTC by Thyme1

2022-05-31 21:15 UTC, matixezor commented on src/api/me.py
> +    user_id = str(current_user['_id'])
W sumie po co castujesz do stringa, skoro później w metodach na nowo tworzysz ObjectId?

2022-05-31 21:16 UTC, matixezor commented on src/infrastructure/database/models/socials/following_database_handler.py
> +        following = (following_collection.find_one({'_id': ObjectId(user_id)}, {'following': 1}))
czemu owrapowane w nawias?

2022-06-01 18:38 UTC, matixezor requested changes

2022-06-01 18:38 UTC, matixezor commented on src/api/socials.py
> +        phrase: str = Query(default=None, min_length=3),
Query(default=..., min_length=3)

2022-06-01 19:17 UTC, Thyme1 commented on src/infrastructure/database/models/user/user_database_handler.py
> +        result = list(collection.find({'username': {'$regex': phrase}, }).skip(offset).limit(limit))
jesteś posiadaczem racji

2022-06-01 21:12 UTC, matixezor approved these changes

2022-06-01 21:33 UTC, merged