feat: add endpoint for lists in guest mode [ALKL-388]
matixezor/AlkohoLove-backend-service pull request #84
Opened 2022-11-25 17:13 UTC by Hiiiiiku

2022-11-27 11:15 UTC, matixezor requested changes

2022-11-27 11:15 UTC, matixezor commented on src/api/user_list.py
> +    for i in range(len(alcohol_list)):
alcohol_list = [validate_object_id(alcohol_id) for alcohol_id in alcohol_list ]

2022-11-27 11:15 UTC, matixezor commented on src/api/user_list.py
> +    path='/guest/',
ostatni / jest niepotrzebny

2022-11-28 20:45 UTC, matixezor submitted a review, later dismissed

2022-11-28 20:45 UTC, matixezor commented on src/infrastructure/database/models/alcohol/alcohol_database_handler.py
> +            alcohol_list: list[str]
to jest lista z ObjectId

2022-11-28 21:58 UTC, Thyme1 approved these changes

2022-11-30 16:16 UTC, merged